### ISSUE TITLE
Mongo.Ecto.truncate is not working

### ISSUE THREAD

**Issue by brado** [michalmuskala/mongodb_ecto#66] opened 2016-01-24 04:20 UTC
I have spent the past day attempting to debug controller tests that were returning errors. These controller tests were generated as part of executing the following command: 
```
mix phoenix.gen.html
```
This creates a number of files, of course, one being a controller and controller test. When running these tests without any alteration, I was receiving several errors, most of them similar to the following: 
```
$ mix test test/controllers/car_controller_test.exs 
Compiled test/support/conn_case.ex
......
  1) test updates chosen resource and redirects when data is valid (Shrek.CarControllerTest)
     test/controllers/car_controller_test.exs:47
     ** (Ecto.MultipleResultsError) expected at most one result but got 3 in query:
     
     from c in Shrek.Car,
       where: c.make == ^"some content",
       where: c.model == ^"some content",
       where: c.year == ^42
     
     stacktrace:
       (ecto) lib/ecto/repo/queryable.ex:47: Ecto.Repo.Queryable.one/4
       test/controllers/car_controller_test.exs:51
```
After several hours determining which tests were causing problems, all of the tests which failed were doing so because there were multiple objects in the database that were matching query criteria, when it was only expecting one (hence the error message above). This was fairly confusing, as in the conn_case.ex file, the following line should have been executing: 
```
      Mongo.Ecto.truncate(Shrek.Repo, [])
```
After repeated tests, I finally constructed a test case which did nothing but that one line of code, and the result is that this line is not truncating the database. That makes sense -- subsequent tests are choking on the data that previous tests have inserted into the database. 

How do I get the truncate to work, or is this a bug? Thx...

**Comment by michalmuskala** [comment] 2016-01-24 10:24
What version of MongoDB are you on?

Possible duplicate of https://github.com/michalmuskala/mongodb_ecto/issues/64

**Comment by brado** [comment] 2016-01-24 14:35
I'm on MongoDB v3.2.0 -- it appears that this is the same issue as #64. Do I need to move back to < 3.2, or is this an easy fix?

**Comment by michalmuskala** [comment] 2016-01-24 14:39
I'm closing this issue in favour of the other one.

**Closed by michalmuskala** 2016-01-24 14:39 UTC
