### ISSUE TITLE
limit: ^n

### ISSUE THREAD

**Issue by leikind** [michalmuskala/mongodb_ecto#40] opened 2015-09-06 12:23 UTC
Not sure whether it is a bug or not.

This works:

```elixir
Query.from(
  c in CodeChallengeEx.Campaign,
  select: c,
  limit: 10
)
|> Repo.all
```

This doesn't:

```elixir
n = 10
Query.from(
  c in CodeChallengeEx.Campaign,
  select: c,
  limit: ^n
)
|> Repo.all
```

```
** (FunctionClauseError) no function clause matching in Mongo.Ecto.NormalizedQuery.offset_limit/1
         (mongodb_ecto) lib/mongo_ecto/normalized_query.ex:272: Mongo.Ecto.NormalizedQuery.offset_limit(%Ecto.Query.QueryExpr{expr: {:^, [], [0]}, file: "/Users/leikind/projects/code_challenge_ex/lib/code_challenge_ex/campaign.ex", line: 20, params: nil})
         (mongodb_ecto) lib/mongo_ecto/normalized_query.ex:220: Mongo.Ecto.NormalizedQuery.limit_skip/1
         (mongodb_ecto) lib/mongo_ecto/normalized_query.ex:65: Mongo.Ecto.NormalizedQuery.find_all/6
         (mongodb_ecto) lib/mongo_ecto.ex:419: Mongo.Ecto.execute/6
                 (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
                 (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
    (code_challenge_ex) lib/code_challenge_ex/clone_service.ex:4: CodeChallengeEx.CloneService.clone/1
```

I am sorry if it not a bug, in this case what am I doing wrong?

**Comment by josevalim** [comment] 2015-09-06 12:26
Duplicate of #39.

**Comment by josevalim** [comment] 2015-09-06 12:26
Thank you @leikind. It is a bug that has been fixed on master.

**Closed by josevalim** 2015-09-06 12:26 UTC
