### ISSUE TITLE
no function clause matching in Mongo.Connection.message/4

### ISSUE THREAD

**Issue by scottmessinger** [michalmuskala/mongodb_ecto#28] opened 2015-07-14 03:29 UTC
I upgraded to the latest version and the other bug was fixed! I can now see output on my browser. However, I'm running into another problem. Is there a method I need to implement?

Repo: https://github.com/scottmessinger/elixir-api-spike

```elixir
[info] GET /api/jurisdictions
[debug] Processing by CommonStandardsProject.JurisdictionController.index/2
  Parameters: %{"format" => "json"}
  Pipelines: [:api]
[debug] FIND coll="jurisdictions" query=%{} projection=%{_id: true, inserted_at: true, title: true, type: true, updated_at: true} [] OK query=2.4ms queue=0.2ms
[info] Sent 200 in 7ms
[error] GenServer #PID<0.978.0> terminating
Last message: {:tcp, #Port<0.166602>, <<176, 19, 0, 0, 167, 90, 1, 0, 166, 90, 1, 0, 1, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0, 58, 0, 0, 0, 85, 0, 0, 0, 2, 95, 105, 100, 0, 33, 0, 0, ...>>}
State: %{auth: [], database: "common-standards-project", opts: [backoff: 1000, port: 27017, otp_app: :common_standards_project, repo: CommonStandardsProject.Repo, adapter: Mongo.Ecto, hostname: 'localhost'], queue: %{}, request_id: 1, socket: #Port<0.166602>, tail: "", timeout: 5000, wire_version: nil, write_concern: [w: 1]}
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Mongo.Connection.message/4
        (mongodb) lib/mongo/connection.ex:282: Mongo.Connection.message(nil, 88742, {:op_reply, [:await_capable], 0, 101, 58, [%{"_id" => "B1339AB05F0347E79200FCA63240F3B2", "title" => "California", "type" => "state"}, %{"_id" => "78D8430CBE88474FAB3CDAAD9094C961", "title" => "Iowa", "type" => "state"}, # < MORE ... >
```

**Comment by michalmuskala** [comment] 2015-07-14 07:34
I think it's something in the driver. It might be fixed in new version, but we can't use it for now with ecto.

/cc @ericmj

**Comment by ericmj** [comment] 2015-07-14 09:34
It seems to be a problem with the driver indeed. @scottmessinger Do you have a way to reproduce?

**Comment by scottmessinger** [comment] 2015-07-14 14:42
@ericmj Thanks for the quick response! The repo is probably be the best way to reproduce. It seems to only affect the index route (and not the "show.json") route.

**Comment by ericmj** [comment] 2015-07-15 13:37
@scottmessinger Can you please provide a working, minimal reproducing case?

I have done the following changes to get the tests to run:

```patch
diff --git a/config/test.exs b/config/test.exs
index d67fa94..0485586 100644
--- a/config/test.exs
+++ b/config/test.exs
@@ -12,8 +12,5 @@ config :logger, level: :warn
 # Configure your database
 config :common_standards_project, CommonStandardsProject.Repo,
   adapter: Ecto.Adapters.Postgres,
-  username: "postgres",
-  password: "postgres",
   database: "common_standards_project_test",
-  pool: Ecto.Adapters.SQL.Sandbox, # Use a sandbox for transactional testing
   size: 1
diff --git a/test/support/channel_case.ex b/test/support/channel_case.ex
index 4b0b9e6..f9adc4d 100644
--- a/test/support/channel_case.ex
+++ b/test/support/channel_case.ex
@@ -33,7 +33,7 @@ defmodule CommonStandardsProject.ChannelCase do

   setup tags do
     unless tags[:async] do
-      Ecto.Adapters.SQL.restart_test_transaction(CommonStandardsProject.Repo, [])
+      Mongo.Ecto.truncate(CommonStandardsProject.Repo)
     end

     :ok
diff --git a/test/support/conn_case.ex b/test/support/conn_case.ex
index 83aa4ab..34acea2 100644
--- a/test/support/conn_case.ex
+++ b/test/support/conn_case.ex
@@ -35,7 +35,7 @@ defmodule CommonStandardsProject.ConnCase do

   setup tags do
     unless tags[:async] do
-      Ecto.Adapters.SQL.restart_test_transaction(CommonStandardsProject.Repo, [])
+      Mongo.Ecto.truncate(CommonStandardsProject.Repo)
     end

     :ok
diff --git a/test/support/model_case.ex b/test/support/model_case.ex
index 352b885..4111815 100644
--- a/test/support/model_case.ex
+++ b/test/support/model_case.ex
@@ -26,7 +26,7 @@ defmodule CommonStandardsProject.ModelCase do

   setup tags do
     unless tags[:async] do
-      Ecto.Adapters.SQL.restart_test_transaction(CommonStandardsProject.Repo, [])
+      Mongo.Ecto.truncate(CommonStandardsProject.Repo)
     end

     :ok
diff --git a/test/test_helper.exs b/test/test_helper.exs
index 5392fa8..b0e05cb 100644
--- a/test/test_helper.exs
+++ b/test/test_helper.exs
@@ -3,4 +3,3 @@ ExUnit.start
 # Create the database, run migrations, and start the test transaction.
 Mix.Task.run "ecto.create", ["--quiet"]
 Mix.Task.run "ecto.migrate", ["--quiet"]
-Ecto.Adapters.SQL.begin_test_transaction(CommonStandardsProject.Repo)
```

But I still get the following errors without the failure in this issue:

```
  1) test does not update chosen resource and renders errors when data is invalid (CommonStandardsProject.JurisdictionControllerTest)
     test/controllers/jurisdiction_controller_test.exs:50
     ** (ArgumentError) cannot convert map/struct to param, key :id contains a nil value
     stacktrace:
       (phoenix) lib/phoenix/param.ex:109: Phoenix.Param.Any.to_param/1
       (common_standards_project) web/router.ex:1: CommonStandardsProject.Router.Helpers.jurisdiction_path/4
       test/controllers/jurisdiction_controller_test.exs:52



  2) test updates and renders chosen resource when data is valid (CommonStandardsProject.JurisdictionControllerTest)
     test/controllers/jurisdiction_controller_test.exs:43
     ** (ArgumentError) cannot convert map/struct to param, key :id contains a nil value
     stacktrace:
       (phoenix) lib/phoenix/param.ex:109: Phoenix.Param.Any.to_param/1
       (common_standards_project) web/router.ex:1: CommonStandardsProject.Router.Helpers.jurisdiction_path/4
       test/controllers/jurisdiction_controller_test.exs:45



  3) test creates and renders resource when data is valid (CommonStandardsProject.JurisdictionControllerTest)
     test/controllers/jurisdiction_controller_test.exs:32
     Expected truthy, got nil
     code: json_response(conn, 200)["data"]["id"]
     stacktrace:
       test/controllers/jurisdiction_controller_test.exs:34



  4) test shows chosen resource (CommonStandardsProject.JurisdictionControllerTest)
     test/controllers/jurisdiction_controller_test.exs:18
     ** (ArgumentError) cannot convert map/struct to param, key :id contains a nil value
     stacktrace:
       (phoenix) lib/phoenix/param.ex:109: Phoenix.Param.Any.to_param/1
       (common_standards_project) web/router.ex:1: CommonStandardsProject.Router.Helpers.jurisdiction_path/4
       test/controllers/jurisdiction_controller_test.exs:20



  5) test deletes chosen resource (CommonStandardsProject.JurisdictionControllerTest)
     test/controllers/jurisdiction_controller_test.exs:56
     ** (ArgumentError) cannot convert map/struct to param, key :id contains a nil value
     stacktrace:
       (phoenix) lib/phoenix/param.ex:109: Phoenix.Param.Any.to_param/1
       (common_standards_project) web/router.ex:1: CommonStandardsProject.Router.Helpers.jurisdiction_path/4
       test/controllers/jurisdiction_controller_test.exs:58
```

**Comment by ericmj** [comment] 2015-07-15 13:39
I also hit the index route and that seems to work:

```
[info] GET /api/jurisdictions
[debug] Processing by CommonStandardsProject.JurisdictionController.index/2
  Parameters: %{"format" => "json"}
  Pipelines: [:api]
[debug] FIND coll="jurisdictions" query=%{} projection=%{_id: true, inserted_at: true, title: true, type: true, updated_at: true} [] OK query=19.8ms queue=10.7ms
[info] Sent 200 in 77ms
```

Can you also give some more information such as mongodb server version?

**Comment by scottmessinger** [comment] 2015-07-17 03:46
@ericmj Thanks again for looking into this. I wish I could put together a more minimal test case, but I'm so new to Elixir and Phoenix, I'm not sure how to. I made the changes and I get the same errors when I run the test suite.

I'm running Mongodb 2.6.5. Could that be the problem?

**Comment by ericmj** [comment] 2015-07-17 12:28
I couldn't reproduce on 2.6.18 either. Please let us know if you find a way for us to reproduce reliably or have any more information. As it is now we don't have enough information to investigate the issue.

**Closed by ericmj** 2015-07-17 12:28 UTC
