### ISSUE TITLE
Support for mongodb 3.2

### ISSUE THREAD

**Issue by blacksails** [michalmuskala/mongodb_ecto#64] opened 2016-01-21 07:22 UTC
Hello

I had an issue in my CI environment, where my tests suddenly failed because the database wasen't properly truncated between tests.

I found out that the problem was that my CI environment used an unsupported version of monogodb.

Version 3.2 has been out since early december. Is it on the roadmap to provide support for the new version? I would be happy to assist making this.

**Comment by ericmj** [comment] 2016-01-22 01:51
Of course it's on the roadmap to support new versions. We appreciate any help we can get, thank you.

**Comment by michalmuskala** [comment] 2016-01-24 10:42
I just tested with MongoDB 3.2.1 and 3.2.0 and everything seemed fine. Could you give me more information on how to reproduce the issue?

**Comment by ivoanjo** [comment] 2016-01-24 11:37
I did a few tests with 3.2 and at least `Mongo.Ecto.truncate` was broken. I saw a lot of specs failing, but not sure if there were any other issues, but after isolating the `truncate` I didn't investigate further.

**Comment by brado** [comment] 2016-01-24 14:33
Yep, I'm on 3.2.0, and truncate is failing for me. It appears this is a duplicate of #66.

**Comment by rafaqueque** [comment] 2016-01-25 10:34
A workaround, for now, is to use `Mongo.Ecto.command(AuthService.Repo, %{dropDatabase: 1})` instead of the regular `Mongo.Ecto.truncate(AuthService.Repo, [])`.

**Comment by michalmuskala** [comment] 2016-01-25 11:44
This is a viable solution, but you need to be aware that dropping database or entire collections will remove any indexes. That's why we provide a separate truncation.

**Comment by brado** [comment] 2016-01-25 12:19
Is this an easy fix that should be coming in the next day or two, or do people need to downgrade MongoDB back to 2.x for the time being?

**Comment by michalmuskala** [comment] 2016-01-25 12:30
I still can't reproduce the issue. Could you tell me what's the output of the `Mongo.Ecto.truncate/2` function? Are all your collections listed there or is there something missing?

**Comment by brado** [comment] 2016-01-25 20:12
@michalmuskala Hey thanks for the reply....I've spent the last several days basically testing mongo_ecto in tandem with phoenix and ecto, so due to my dire need to actually produce on my project I reverted back to MongoDB 2.6.11 to move forward (truncate works there). I was originally using MongoDB 3.2 when I encountered this problem, and though I cannot answer your question off the top of my head, I can tell you that didn't appear to be any impact when browsing data in the Mongo database.

If you perceive this issue to be a potentially simple one to fix, and having the answer to the question you asked would result in an immediate fix, I suppose I could revert back to MongoDB 3.2 and give it a go quickly. But I've lingered a little long in this testing, and I'm very pressed for time to make progress on what all of this testing was actually for -- so if the fix is a longer term one (weeks) then I could revisit this, probably later this week or next week after I hit a milestone with my work. 

Using Mongo 3.2 would be ideal, but I gained from discussion on other issues that we were looking at a month to get support for this / current version of Ecto, so if that's the case, I can revisit in a week if that works. If not, let me know, and I'll see what I can do. Thx.

**Comment by brado** [comment] 2016-01-25 21:14
@michalmuskala Maybe I can help here now -- the easiest way I know how to reproduce the problem is to create a new phoenix project using: 
```
mix phoenix.new --database mongodb
```
and then change mix.exs to use these dependencies: 
```
      {:phoenix, "~> 1.1"},
      {:phoenix_ecto, "~> 1.2.0"},
      {:phoenix_html, "~> 2.3"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:mongodb_ecto, github: "michalmuskala/mongodb_ecto"},
      {:cowboy, "~> 1.0"},
      {:exrm, "~> 1.0.0-rc7"},
      {:gettext, "~> 0.9"}
```
Then use `mix phoenix.gen.html` with any old model object like this: 
```
mix phoenix.gen.html Port ports portNumber:integer protocol:string banner:string
```
You'll need to change your repo to use mongodb.ecto as its adapter, of course, but do the above and with MongoDB 3.2 run your generated tests and they should blow up due to the conn_case.ex file's truncate line that looks like this: 
```
Mongo.Ecto.truncate(MyApp.Repo, [])
```
not working. In addition to the test which fails because of the sample data for the ID which we've talked about in another issue, you should have one or more test failures due to multiple documents being found when only one was expected (because the truncate doesn't work). 

I hope that helps.

**Comment by kwojtaszek** [comment] 2016-03-02 23:04
see #73

**Closed** 2016-03-03 18:44 UTC
