### ISSUE TITLE
Are remote mongo databases supported?

### ISSUE THREAD

**Issue by Morganjackson** [michalmuskala/mongodb_ecto#90] opened 2016-08-10 01:35 UTC
I have a mongo database running on compose.io but so far I haven't be able to get it running for more than a few minutes.

I have seen a couple of other issues (https://github.com/michalmuskala/mongodb_ecto/issues/87 https://github.com/michalmuskala/mongodb_ecto/issues/52 ) which appear to have the same problem but it looks like the issues were closed but not resolved.

This is the error:

``` yml
[error] #PID<0.687.0> running Demo.Endpoint terminated
Server: johndoe.localhost:4000 (http)
Request: GET /
** (exit) exited in: GenServer.call(#PID<0.542.0>, {:find, "users", [{"$query", [username: "johndoe"]}, {"$orderby", %{}}], %{_id: true}, [batch_size: 1000]}, 5000)
    ** (EXIT) time out
[error] Mongo tcp error (galaga.3.mongolayer.com:10161): connection timed out
[error] Mongo tcp error (galaga.3.mongolayer.com:10161): closed
```

I have tried various configs including setting the full mongodb:// url but it always times out after being idle for a minute or so.

This is what I have now:

``` exs
config :demo, Demo.MongoRepo,
  adapter: Mongo.Ecto,
    database: "backup",
    port: 10161,
    username: "username",
    password: "password",
    hostname: "galaga.3.mongolayer.com",
    timeout: :infinity,
    connect_timeout: :infinity,
    pool_timeout: :infinity,
    socket_options: [keepalive: true]
```

I'm using:

:mongodb_ecto, "0.1.4"
:phoenix_ecto, "1.2.0"

The compose DB is running mongo 3.0.11

I have asked asked around on the forums, slack etc but so far no luck so I'm at the end of the road with this! 

I know there are lot of Meteor users who are looking to move over to phoenix and a lot of them use compose.io so if this isn't supported or if its not on the roadmap we should make it clear on the readme.

**Comment by Morganjackson** [comment] 2016-08-10 01:39
Just to be 100% clear, all the settings that I have tried do work and the phoenix application connects perfectly until I leave it for a minute or so.

**Comment by scottmessinger** [comment] 2016-08-10 04:00
@Morganjackson I'm also connecting to a database on Compose and it's working. I don't have a timeout, connect_timeout, pool_timeout, or socket_options set. I'm not sure if those are affecting what's going on...

**Comment by Morganjackson** [comment] 2016-08-10 04:07
@scottmessinger thanks Scott, at least I now know that it can work! 

originally I started with just the basics but it didn't work. 

Are you using 

```ex
url: mongodb://etc
``` 

or

```ex
 database: "backup",
    port: 10161,
    username: "username",
    password: "password",
    hostname: "galaga.3.mongolayer.com",
```

Both ways give me the same result so I'm not sure it matters.

**Comment by scottmessinger** [comment] 2016-08-10 04:13
@Morganjackson I'm using the second form:

```elixir
config :my_app, MyApp.Repo,
  adapter: Mongo.Ecto,
  database: System.get_env("DB_NAME"),
  username: System.get_env("DB_USERNAME"),
  password: System.get_env("DB_PASSWORD"),
  port:     String.to_integer(System.get_env("DB_PORT")),
  hostname: System.get_env("DB_HOST")
```

I'm using one of the WiredTiger, MongoDB 3.2 deployments. I wonder if it's a MongoDB version issue going on.

**Comment by Morganjackson** [comment] 2016-08-10 04:21
@scottmessinger thanks. 

> I'm using one of the WiredTiger, MongoDB 3.2 deployments. I wonder if it's a MongoDB version issue going on.

 I was wondering the same thing but unfortunately I'm stuck on 3.0 for now. 

Now that I know that WiredTiger works for you, I will try restore a backup on a WT deployment and see if that makes any difference

**Comment by michalmuskala** [comment] 2017-03-07 18:05
Since it didn't saw activity in a long time, I'm going to close it. Please reopen (or ping here) if the issue is still relevant.

**Closed by michalmuskala** 2017-03-07 18:05 UTC
