### ISSUE TITLE
Exception raised when inserting an Ecto.Model containing a map containing Ecto.DateTime fields

### ISSUE THREAD

**Issue by frferrari** [michalmuskala/mongodb_ecto#59] opened 2015-12-17 22:52 UTC
Hi,
(I am new to Elixir) I experiment a problem when inserting an Ecto.Model containing a map containing end_date and start_date Ecto.DataTime fields (see below an extract simplified version of the map). I get the following message  when inserting into MongoDB with the insert! function :

%ArgumentError{message: "Invalid expression for MongoDB adapter in insert command"}

As soon as I replace the end_date and start_date Ecto.DateTime fields by :integer fields containing timestamps then the insert works, and the created_at field located in the %Event map of type Ecto.DateTime is correctly persisted as an ISODate field into Mongo.

Could you give some advice about what I should do to solve this problem ? Thanks for your work.

```
%Event{__meta__: #Ecto.Schema.Metadata<:built>, the_id: 135,
created_at: #Ecto.DateTime<2010-10-19T18:30:05Z>,
event_data: %{area_id: 230, currency_code: "EUR", 
end_date: #Ecto.DateTime<2013-09-04T00:50:03Z>, 
is_closed: true,
start_date: #Ecto.DateTime<2013-08-28T00:50:03Z>,
stock: 1, type_id: 1, year: 2009}, event_type: "the_created_event"}
```

Below is the %Event module used to persist data :

```
defmodule Event do 
	use Ecto.Model

	@primary_key {:id, :binary_id, autogenerate: true}
  schema "my_events" do
  	field :event_type, :string
        field :event_data, :map
  	field :the_id, :integer

    timestamps([inserted_at: :created_at, updated_at: false])
  end
end
``̀`

**Comment by ericmj** [comment] 2015-12-17 23:09
This should be fixed in this PR: https://github.com/michalmuskala/mongodb_ecto/pull/58. It would be a lot of help for us if you could try out the PR branch and confirm if it works. Thanks!

**Comment by frferrari** [comment] 2015-12-18 11:16
Hi Eric,
As I am new to Elixir and even Github (yes :-) I am not sure about how to extract PR#58 in my current project, here is what I have done but it is not working :

cd deps/mongodb_ecto
git fetch origin pull/58/head:mymaster
git checkout mymaster
cd ../..
mix deps.get # I had to launch a mix deps.get otherwise I the project won't start

ls -l deps/mongodb_ecto/lib/mongo_ecto.ex
-rw-rw-r-- 1 francois francois 26310 déc.  18 11:56 mongo_ecto.ex

Here is the content of my deps definition in mix.exs

  defp deps do
    [{:phoenix, "~> 1.0.3"},
     {:phoenix_ecto, "~> 1.1"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"},
     {:mariaex, ">= 0.0.0"},
     {:gproc, "~> 0.3.1"},
     {:mongodb_ecto, github: "michalmuskala/mongodb_ecto"},
     {:poison, "~> 1.5"}]
  end

Could you explain me how to extract PR#58 locally (configurable in my mix.exs/deps function ?)

Thanks,

**Comment by michalmuskala** [comment] 2015-12-18 11:18
The PR was merged into master.

**Comment by frferrari** [comment] 2015-12-18 12:11
I checked that I am working with the master branch by issuing a "git branch" command in the mongodb_ecto directory, I got back "master".

Then I tried again to insert an Ecto.Model containing a map containing Ecto.DateTime but I still got the same issue "%ArgumentError{message: "Invalid expression for MongoDB adapter in insert command"}"

I have a question :
when I insert a map whose keys are atoms, those atoms are persisted as strings which is ok of course. But when I read the same map, I get back a map whose keys are strings and I have to convert those keys to atoms because I want to make a struct(Event, mongodata) and struct() seems not to support keys expressed as strings. Is there a way to read a map and to automatically get back keys expressed as atoms ?

**Comment by tomjoro** [comment] 2016-01-14 22:29
Re atoms as keys: I don't know if this helps, but the Ruby drivers do exactly the same thing. https://github.com/mongodb/mongo-ruby-driver/wiki/FAQ#i-see-that-bson-supports-a-symbol-type-does-this-mean-that-i-can-store-ruby-symbols-in-mongodb

The problem is that MongoDB only stores keys as strings. So when you are pulling things out of MongoDB there is really no way to determine if the key was originally a string or if it was an atom  (or symbol in Ruby). There's different strategies in Ruby to deal with this, so you might check that out.

**Comment by ericmj** [comment] 2016-01-15 13:04
The symbol type in bson is deprecated and should not be used. In fact the driver only supports decoding them but does not support encoding to symbols.

If you want a map with atom keys you can implement a custom type in Ecto that does the conversion.

**Closed** 2016-01-31 09:55 UTC
